name: Merge request pipeline

on:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Kotlin Linter
        run: ./gradlew lintKotlin

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Build
        run: ./gradlew build
